In [1]:
import numpy as np

def k_means(X, K, max_iterations=100):
    # Initialize centroids randomly
    centroids = X[np.random.choice(range(len(X)), size=K, replace=False)]

    for _ in range(max_iterations):
        # Assign each data point to the nearest centroid
        labels = np.argmin(np.linalg.norm(X[:, np.newaxis] - centroids, axis=-1), axis=-1)

        # Update the centroids based on the mean of the assigned points
        new_centroids = np.array([X[labels == k].mean(axis=0) for k in range(K)])

        # Check if the centroids have converged
        if np.all(centroids == new_centroids):
            break

        centroids = new_centroids

    return centroids, labels

In [2]:
def lms(X, y, learning_rate=0.01, max_iterations=100):
    # Add a bias term to the input data
    X = np.column_stack((np.ones(len(X)), X))

    # Initialize weights randomly
    weights = np.random.randn(X.shape[1])

    for _ in range(max_iterations):
        # Make predictions
        predictions = np.dot(X, weights)

        # Calculate the error
        error = y - predictions

        # Update the weights
        weights += learning_rate * np.dot(X.T, error)

    return weights

In [8]:
from sklearn.cluster import KMeans
from sklearn.linear_model import LinearRegression
from sklearn.metrics import silhouette_score, mean_squared_error

# Function approximation problem
X = np.linspace(0, 10, 100).reshape(-1, 1)
y = np.sin(X)

# Using the custom K-means algorithm
custom_centroids, custom_labels = k_means(X, K=3)
# Using the built-in K-means algorithm
sklearn_kmeans = KMeans(n_clusters=3)
sklearn_labels = sklearn_kmeans.fit_predict(X)

# Using the custom LMS algorithm
custom_weights = lms(X, y.flatten())
# Using the built-in Linear Regression algorithm
sklearn_regression = LinearRegression()
sklearn_regression.fit(X, y)

# Compare the results
print("Custom K-means centroids:\n", custom_centroids)
print("#  These are the centroids obtained from the my custom K-means algorithm.\nEach row represents a centroid, and the number of columns depends on the dimensionality of the data.")

print("Scikit-learn K-means centroids:\n", sklearn_kmeans.cluster_centers_)
print("#  These are the centroids obtained from the scikit-learn K-means algorithm.")

print("Custom LMS weights:\n", custom_weights)
print("#  These are the weights obtained from the my LMS (Least Mean Squares) algorithm.\nThe custom_weights variable contains the learned weights for the linear regression problem.")

print("Scikit-learn Linear Regression weights:\n", sklearn_regression.coef_)
print("#  These are the weights obtained from the scikit-learn Linear Regression algorithm.")

Custom K-means centroids:
 [[4.84848485]
 [1.56565657]
 [8.28282828]]
#  These are the centroids obtained from the my custom K-means algorithm.
Each row represents a centroid, and the number of columns depends on the dimensionality of the data.
Scikit-learn K-means centroids:
 [[8.38383838]
 [1.66666667]
 [5.05050505]]
#  These are the centroids obtained from the scikit-learn K-means algorithm.
Custom LMS weights:
 [2.79546184e+151 1.85917693e+152]
#  These are the weights obtained from the my LMS (Least Mean Squares) algorithm.
The custom_weights variable contains the learned weights for the linear regression problem.
Scikit-learn Linear Regression weights:
 [[-0.01730202]]
#  These are the weights obtained from the scikit-learn Linear Regression algorithm.


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [9]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Classification problem
X, y = make_classification(n_samples=100, n_features=2, n_informative=2, n_redundant=0, random_state=42)

# Using the custom K-means algorithm
custom_centroids, custom_labels = k_means(X, K=2)
# Using the built-in K-means algorithm
sklearn_kmeans = KMeans(n_clusters=2)
sklearn_labels = sklearn_kmeans.fit_predict(X)

# Using the custom LMS algorithm
custom_weights = lms(X, y, learning_rate=0.01, max_iterations=100)
# Using the built-in Logistic Regression algorithm
sklearn_classification = LogisticRegression()
sklearn_classification.fit(X, y)

# Make predictions
custom_predictions = np.argmax(np.dot(np.column_stack((np.ones(len(X)), X)), custom_weights))
sklearn_predictions = sklearn_classification.predict(X)

# Compare the results
print("My K-means centroids:\n", custom_centroids)
print("#  These are the centroids obtained from the custom K-means algorithm.")

print("Scikit-learn K-means centroids:\n", sklearn_kmeans.cluster_centers_)
print("#  These are the centroids obtained from the scikit-learn K-means algorithm.")

print("Custom LMS weights:\n", custom_weights)
print("#  These are the weights obtained from the my LMS (Least Mean Squares) algorithm.")

print("Scikit-learn Logistic Regression weights:\n", sklearn_classification.coef_)
print("#  These are the weights obtained from the scikit-learn Logistic Regression algorithm.")

print("Custom K-means accuracy:", accuracy_score(y, custom_labels))
print("#  This is the accuracy of the my K-means algorithm achieved by comparing the predicted labels with the true labels.")

print("Scikit-learn K-means accuracy:", accuracy_score(y, sklearn_labels))
print("#  This is the accuracy of the scikit-learn K-means algorithm achieved by comparing the predicted labels with the true labels.")

print("Custom LMS accuracy:", accuracy_score(y, custom_labels))
print("#  This is the accuracy of the my LMS algorithm achieved by comparing the predicted labels with the true labels.")

print("Scikit-learn Logistic Regression accuracy:", accuracy_score(y, sklearn_predictions))
print("#  This is the accuracy of the scikit-learn Logistic Regression algorithm achieved by comparing the predicted labels with the true labels.")

My K-means centroids:
 [[-1.29452448 -0.78043004]
 [ 0.88963137  0.48091756]]
#  These are the centroids obtained from the custom K-means algorithm.
Scikit-learn K-means centroids:
 [[-1.34447921 -0.94487184]
 [ 0.77933551  0.50032721]]
#  These are the centroids obtained from the scikit-learn K-means algorithm.
Custom LMS weights:
 [-9.22461999e+06  1.65535993e+08  1.35646339e+08]
#  These are the weights obtained from the my LMS (Least Mean Squares) algorithm.
Scikit-learn Logistic Regression weights:
 [[ 3.23218612 -0.84604963]]
#  These are the weights obtained from the scikit-learn Logistic Regression algorithm.
Custom K-means accuracy: 0.84
#  This is the accuracy of the my K-means algorithm achieved by comparing the predicted labels with the true labels.
Scikit-learn K-means accuracy: 0.8
#  This is the accuracy of the scikit-learn K-means algorithm achieved by comparing the predicted labels with the true labels.
Custom LMS accuracy: 0.84
#  This is the accuracy of the my LMS al

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
